export const ADD = "ADD";
export const TRIGGER_ADDING = "TRIGGER_ADDING";
export const UPDATE = "UPDATE";
export const REMOVE = "REMOVE";

export const TOGGLE_PASSING = "TOGGLE_PASSING";

export const TOGGLE_CURRENT_TASK = "TOGGLE_CURRENT_TASK";
export const MODIFY_CURRENT_TASK = "MODIFY_CURRENT_TASK";
export const CLEAR_CURRENT_TASK = "CLEAR_CURRENT_TASK";